### ISSUE TITLE
ui引入报错

### ISSUE THREAD

**Issue by RubbbbbY** [yunfeihuang/vx-ui#10]
![image](https://user-images.githubusercontent.com/19768528/50284926-8cc6fc80-0495-11e9-91dd-121669870270.png)

**Comment by yunfeihuang** [comment]
npm install element-ui

**Comment by RubbbbbY** [comment]
单个组件引入不行，我现在只想用sticky这个组件，但是报错了
![image](https://user-images.githubusercontent.com/19768528/50286614-ec73d680-049a-11e9-9c67-79157de91218.png)
gen跟button组件例子那样引入的
![image](https://user-images.githubusercontent.com/19768528/50286653-08777800-049b-11e9-9ff5-de61120b142c.png)

**Comment by RubbbbbY** [comment]
> 需要安装element ui包:npm install element-ui --save

能帮我看下什么问题吗

**Comment by RubbbbbY** [comment]
> import sticky from 'vx-ui/lib/sticky'这种方式试试

试过了，还是直接报错
![image](https://user-images.githubusercontent.com/19768528/50319810-3cd34e80-0504-11e9-9223-8b364b8f4e33.png)
![image](https://user-images.githubusercontent.com/19768528/50319813-465cb680-0504-11e9-9c79-1c8a268fd180.png)

**Comment by yunfeihuang** [comment]
抱歉，现在要这么写了Vue.component(sticky.componentName, sticky) 遇到这样的问题你可以直接打印sticky出来了解里面内容

**Comment by RubbbbbY** [comment]
> 抱歉，现在要这么写了Vue.component(sticky.componentName, sticky) 遇到这样的问题你可以直接打印sticky出来了解里面内容

可以了，感谢！
