### ISSUE TITLE
打开弹出层能否不变动地址栏

### ISSUE THREAD

**Issue by kuangzhibin** [yunfeihuang/vx-ui#12]
打开弹出层时地址栏会添加如‘?popup=q319i3zhr8f’这样的字段，能否去除掉？

**Comment by kuangzhibin** [comment]
主要想去掉select组件的
popup有history属性可以关闭
select可以通过popup-direction控制popup的位置
希望popup-history能控制是否产生浏览器历史记录

**Comment by yunfeihuang** [comment]
设置:history="false"

**Comment by yunfeihuang** [comment]
Select下拉框组件设置:popup-props="{history: false}"后就不产生浏览器地址历史记录，请更新最新的vx-ui版本，非常感谢您的建议和反馈
