### ISSUE TITLE
请问脚手架4以后的怎么引入啊，老是报错

### ISSUE THREAD

**Issue by LDWBFS** [yunfeihuang/vx-ui#16]

**Comment by yunfeihuang** [comment]
报什么错误？你是不是用vue3了？

**Comment by LDWBFS** [comment]
恩恩，我改回vue2了，可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月6日(星期四) 中午11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yunfeihuang/vx-ui] 请问脚手架4以后的怎么引入啊，老是报错 (#16)





 
报什么错误？你是不是用vue3了？
