### ISSUE TITLE
作者进来看下，运行出错。

### ISSUE THREAD

**Issue by zengjielin** [yunfeihuang/vx-ui#6]
1、按照文档操作，
npm install vx-ui --save-dev
2、然后再main.js上引入
import 'vx-ui/lib/style/theme/index.css'
import VxUI from 'vx-ui'
Vue.use(VxUI)
3、运行项目出错
4、出错代码
 ERROR  Failed to compile with 7 errors                                                                                                                                                                 16:32:58
These dependencies were not found:

* photoswipe/dist/default-skin/default-skin.css in ./node_modules/vx-ui/lib/index.js
* photoswipe/dist/photoswipe-ui-default in ./node_modules/vx-ui/lib/index.js
* photoswipe/dist/photoswipe.css in ./node_modules/vx-ui/lib/index.js
* photoswipe/dist/photoswipe.min.js in ./node_modules/vx-ui/lib/index.js
* qrcodejs2 in ./node_modules/vx-ui/lib/index.js
* swiper/dist/css/swiper.min.css in ./node_modules/vx-ui/lib/index.js
* swiper/dist/js/swiper.min.js in ./node_modules/vx-ui/lib/index.js

To install them, you can run: npm install --save photoswipe/dist/default-skin/default-skin.css photoswipe/dist/photoswipe-ui-default photoswipe/dist/photoswipe.css photoswipe/dist/photoswipe.min.js qrcodejs2
swiper/dist/css/swiper.min.css swiper/dist/js/swiper.min.js
![1]

**Comment by yunfeihuang** [comment]
安装一下这三个包：
npm install photoswipe qrcodejs2 swiper

**Comment by zengjielin** [comment]
感谢
